#!/usr/bin/env ruby
#^syntax detection

#Install cookbooks using `librarian-chef update`

site 'http://community.opscode.com/api/v1'

#Packages
cookbook 'apache2', '~> 3.0.1'
cookbook 'apt', '~> 2.6.1'
cookbook 'build-essential', '~> 2.1.3'
cookbook 'composer', '~> 2.0.0'
cookbook 'git', '~> 4.1.0'
cookbook 'mysql', '~> 6.0.15'
cookbook 'openssl'
cookbook 'php'
